### ISSUE TITLE
List index out of range after ft >> 7 in line 89 (ft becomes 15, thats > 9)

### ISSUE THREAD

**Issue by kosumosuSpb** [Spinlogic/AMR-WB_extractor#2]
Hi!

I noticed, that on some files script crushes with this:

```
Number of packets read from pcap: 518
AMR samples: 0, AMR-WB samples: 100, EVS samples: 0
Traceback (most recent call last):
  File "./pcap_parser.py", line 384, in <module>
    storePayloadIetf(ofile, codec, rtp.load)
  File "./pcap_parser.py", line 89, in storePayloadIetf
    if len(buf) >= codec_ft[ft]:    # remove padding
IndexError: list index out of range
```
it happens because after ft = ft >> 7 ft becomes > 9 (15)

I dont know actually how extractor works exactly, can anyone help? :)

**Comment by kosumosuSpb** [comment]
I found that its happens with files that has 74 byte == 21-24. 
If their == f1 or f4 - everything is ok

**Comment by Spinlogic** [comment]
nothing to fix, looks like.
